
/api/products:
 get:
   tags:
   - Products
   summary: List Product
   security:
     - bearerAuth: []
   responses:
     200:
       description: Get all products
       content:
         application/json:
           schema:
             type: array
             items:
               $ref: '#/components/schemas/Product'
     400:
       description: Bad request
       content:
         application/json:
           schema:
             type: object
             properties:
               error:
                 type: string
                 example: error de llamado a db
     401:
       description: Unauthorized userr, necesita token valido